-- =====================================================================
-- ReadB DB Schema (Supabase / PostgreSQL)
-- ReadB 신규 Supabase PostgreSQL DB 초기 생성 스키마 
--
-- 새 DB에 처음 한 번 실행
-- 과거 db/migrations 파일은 이전 DB의 변경 기록이며, 이 스키마로 생성한 새 DB에는 실행하지 않음 
-- ---------------------------------------------------------------------
BEGIN;

CREATE TABLE public.users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    role            VARCHAR(255) NOT NULL,
    job_title       VARCHAR(100),
    team_id         BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('LEADER', 'MEMBER'))
);

CREATE TABLE public.teams (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    leader_id       BIGINT NOT NULL,
    invite_code     VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_teams_invite_code UNIQUE (invite_code),
    CONSTRAINT fk_teams_leader FOREIGN KEY (leader_id) REFERENCES public.users (id)
);

-- users and teams refer to each other; add this FK after both tables exist.
ALTER TABLE public.users
    ADD CONSTRAINT fk_users_team FOREIGN KEY (team_id) REFERENCES public.teams (id);

CREATE TABLE public.meetings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id         BIGINT NOT NULL,
    title           VARCHAR(100) NOT NULL DEFAULT '1:1 Meeting',
    leader_id       BIGINT NOT NULL,
    member_id       BIGINT NOT NULL,
    scheduled_at    TIMESTAMP WITHOUT TIME ZONE,
    status          VARCHAR(255) NOT NULL DEFAULT 'CREATED',
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_meetings_team FOREIGN KEY (team_id) REFERENCES public.teams (id),
    CONSTRAINT fk_meetings_leader FOREIGN KEY (leader_id) REFERENCES public.users (id),
    CONSTRAINT fk_meetings_member FOREIGN KEY (member_id) REFERENCES public.users (id),
    CONSTRAINT chk_meetings_status CHECK (status IN (
        'CREATED', 'TRANSCRIBING', 'ANALYZING', 'COMPLETED', 'FAILED'
    ))
);

CREATE TABLE public.recordings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id      BIGINT NOT NULL,
    file_url        TEXT,
    duration_sec    INTEGER,
    transcript      TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_recordings_meeting UNIQUE (meeting_id),
    CONSTRAINT fk_recordings_meeting FOREIGN KEY (meeting_id) REFERENCES public.meetings (id)
);

CREATE TABLE public.surveys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id      BIGINT NOT NULL,
    member_id       BIGINT NOT NULL,
    scores          JSONB,
    submitted_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_surveys_meeting_member UNIQUE (meeting_id, member_id),
    CONSTRAINT fk_surveys_meeting FOREIGN KEY (meeting_id) REFERENCES public.meetings (id),
    CONSTRAINT fk_surveys_member FOREIGN KEY (member_id) REFERENCES public.users (id)
);

CREATE TABLE public.analyses (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id            BIGINT NOT NULL,
    alignment_gap         DOUBLE PRECISION,
    alignment_gap_detail  TEXT,
    honesty_gap           DOUBLE PRECISION,
    execution_gap         DOUBLE PRECISION,
    safety_score          DOUBLE PRECISION,
    speech_acts           JSONB,
    blocker_keywords      JSONB,
    leader_feedback       JSONB,
    member_feedback       JSONB,
    career_tags           JSONB,
    talk_ratio            JSONB,
    baseline_data         JSONB,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_analyses_meeting UNIQUE (meeting_id),
    CONSTRAINT fk_analyses_meeting FOREIGN KEY (meeting_id) REFERENCES public.meetings (id)
);

CREATE TABLE public.promises (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id      BIGINT NOT NULL,
    owner_id        BIGINT NOT NULL,
    content         TEXT NOT NULL,
    context         TEXT,
    category        VARCHAR(50),
    deadline        DATE,
    status          VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_promises_meeting FOREIGN KEY (meeting_id) REFERENCES public.meetings (id),
    CONSTRAINT fk_promises_owner FOREIGN KEY (owner_id) REFERENCES public.users (id),
    CONSTRAINT chk_promises_status CHECK (status IN ('PENDING', 'DONE', 'MISSED'))
);

CREATE TABLE public.career_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    meeting_id      BIGINT,
    event_type      VARCHAR(255) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    evidence        JSONB,
    occurred_at     TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_career_events_user FOREIGN KEY (user_id) REFERENCES public.users (id),
    CONSTRAINT fk_career_events_meeting FOREIGN KEY (meeting_id) REFERENCES public.meetings (id),
    CONSTRAINT chk_career_events_type CHECK (event_type IN (
        'ACHIEVEMENT', 'INITIATIVE', 'GROWTH', 'CONTRIBUTION',
        'FEEDBACK', 'LEADER_ENDORSEMENT'
    ))
);

CREATE TABLE public.action_plans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id      BIGINT NOT NULL,
    leader_id       BIGINT NOT NULL,
    content         TEXT NOT NULL,
    is_completed    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_action_plans_meeting FOREIGN KEY (meeting_id) REFERENCES public.meetings (id),
    CONSTRAINT fk_action_plans_leader FOREIGN KEY (leader_id) REFERENCES public.users (id)
);

CREATE TABLE public.team_coaching_cache (
    team_id         BIGINT PRIMARY KEY,
    signature       TEXT NOT NULL,
    payload         TEXT NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_team_coaching_cache_team FOREIGN KEY (team_id) REFERENCES public.teams (id)
);

CREATE TABLE public.team_blocker_cache (
    team_id         BIGINT PRIMARY KEY,
    signature       TEXT NOT NULL,
    payload         TEXT NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_team_blocker_cache_team FOREIGN KEY (team_id) REFERENCES public.teams (id)
);

-- Preserve useful indexes from the historical schema and add indexes for
-- the foreign keys introduced above. PK and UNIQUE constraints index themselves.
CREATE INDEX idx_users_team_id ON public.users (team_id);
CREATE INDEX idx_users_role ON public.users (role);
CREATE INDEX idx_teams_leader_id ON public.teams (leader_id);
CREATE INDEX idx_meetings_team_id ON public.meetings (team_id);
CREATE INDEX idx_meetings_leader_id ON public.meetings (leader_id);
CREATE INDEX idx_meetings_member_id ON public.meetings (member_id);
CREATE INDEX idx_meetings_status ON public.meetings (status);
CREATE INDEX idx_surveys_meeting_id ON public.surveys (meeting_id);
CREATE INDEX idx_surveys_member_id ON public.surveys (member_id);
CREATE INDEX idx_promises_meeting_id ON public.promises (meeting_id);
CREATE INDEX idx_promises_owner_id ON public.promises (owner_id);
CREATE INDEX idx_promises_status ON public.promises (status);
CREATE INDEX idx_career_events_user_id ON public.career_events (user_id);
CREATE INDEX idx_career_events_meeting_id ON public.career_events (meeting_id);
CREATE INDEX idx_career_events_type ON public.career_events (event_type);
CREATE INDEX idx_action_plans_meeting_id ON public.action_plans (meeting_id);
CREATE INDEX idx_action_plans_leader_id ON public.action_plans (leader_id);

-- The Spring Boot application uses a direct PostgreSQL connection. Keep the
-- tables closed to anon/authenticated Data API roles if that API is enabled
-- later; no client-facing RLS policies are needed for the current design.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recordings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.career_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.action_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_coaching_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_blocker_cache ENABLE ROW LEVEL SECURITY;

COMMIT;
